version : 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/gooroomi/
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/gooroomi
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 750
  - object: /home/ubuntu/gooroomi/gooroomi-prod-logs
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 750
  - object: /home/ubuntu/gooroomi/*.jar
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 750

hooks:
    ApplicationStart:
      - location: deploy.sh
        timeout: 60
        runas: root
