version: '3'

services:
  gooroomi-green:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gooroomi-green
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - gooroomi-network
    restart: always
    volumes:
      - /home/ubuntu/gooroomi/gooroomi-prod-logs:/app/logs

networks:
  gooroomi-network:
    driver: bridge 